//! Hook generation for workspace doc enforcement.
//!
//! Reads [workspace.docs.rules] from corvia.toml and generates:
//! - .corvia/hooks/doc-placement-check.sh (PreToolUse validation)
//! - repos/*/.git/hooks/post-commit (git-triggered incremental re-index)
//! - .claude/settings.json merge (hook registration)

use corvia_common::config::{CorviaConfig, DocsRulesConfig};
use corvia_common::errors::Result;
use std::path::Path;

pub fn generate_hooks(root: &Path, config: &CorviaConfig) -> Result<()> {
    let ws = config.workspace.as_ref()
        .ok_or_else(|| corvia_common::errors::CorviaError::Config("Not a workspace".into()))?;

    let rules = ws.docs.as_ref()
        .and_then(|d| d.rules.as_ref())
        .cloned()
        .unwrap_or_default();

    generate_placement_hook(root, &rules)?;
    generate_post_commit_hooks(root, ws, config)?;
    merge_claude_settings(root)?;

    println!("Generated enforcement hooks from corvia.toml");
    Ok(())
}

fn generate_placement_hook(root: &Path, rules: &DocsRulesConfig) -> Result<()> {
    let hook_dir = root.join(".corvia/hooks");
    std::fs::create_dir_all(&hook_dir)
        .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to create hooks dir: {e}")))?;

    let blocked_cases: String = rules.blocked_paths.iter()
        .map(|p| format!("  {})\n    echo \"BLOCKED: '$FILE_PATH' matches blocked path '{}'.\" >&2\n    exit 2\n    ;;", p, p))
        .collect::<Vec<_>>()
        .join("\n");

    let script = format!(r#"#!/usr/bin/env bash
set -euo pipefail
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.file_path // empty')
[ -z "$FILE_PATH" ] && exit 0
case "$FILE_PATH" in *.md|*.mdx|*.rst) ;; *) exit 0 ;; esac
case "$FILE_PATH" in
{blocked_cases}
  repos/*/docs/*|docs/decisions/*|docs/learnings/*|docs/marketing/*|docs/plans/*)
    exit 0 ;;
esac
echo "NOTE: '$FILE_PATH' is in an unusual location for docs." >&2
exit 0
"#);

    let path = hook_dir.join("doc-placement-check.sh");
    std::fs::write(&path, script)
        .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to write hook: {e}")))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to chmod: {e}")))?;
    }

    println!("  Created: {}", path.display());
    Ok(())
}

fn generate_post_commit_hooks(
    root: &Path,
    ws: &corvia_common::config::WorkspaceConfig,
    _config: &CorviaConfig,
) -> Result<()> {
    for repo in &ws.repos {
        let git_hooks_dir = root.join(&ws.repos_dir).join(&repo.name).join(".git/hooks");
        if !git_hooks_dir.exists() {
            println!("  Skipped: {} (no .git directory)", repo.name);
            continue;
        }

        // Use xargs to safely handle filenames with newlines/spaces
        let hook = r#"#!/usr/bin/env bash
# Generated by: corvia workspace init-hooks
changed=$(git diff-tree --no-commit-id --name-only -r HEAD)
docs_changed=$(echo "$changed" | grep -E '\.(md|toml|yaml|json|rs|py|ts|js)$' || true)
if [ -n "$docs_changed" ]; then
    echo "$docs_changed" | xargs corvia ingest --incremental --files &
fi
"#;

        let path = git_hooks_dir.join("post-commit");
        std::fs::write(&path, hook)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to write hook: {e}")))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
                .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to chmod: {e}")))?;
        }

        println!("  Created: {}", path.display());
    }
    Ok(())
}

/// Merge the PreToolUse Write|Edit hook into .claude/settings.json
fn merge_claude_settings(root: &Path) -> Result<()> {
    let settings_path = root.join(".claude/settings.json");
    let mut settings: serde_json::Value = if settings_path.exists() {
        let content = std::fs::read_to_string(&settings_path)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to read settings: {e}")))?;
        serde_json::from_str(&content)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to parse settings: {e}")))?
    } else {
        serde_json::json!({})
    };

    // Ensure hooks.PreToolUse array exists
    let hooks = settings.as_object_mut().unwrap()
        .entry("hooks").or_insert(serde_json::json!({}));
    let pre_tool = hooks.as_object_mut().unwrap()
        .entry("PreToolUse").or_insert(serde_json::json!([]));
    let arr = pre_tool.as_array_mut().unwrap();

    // Check if Write|Edit hook already registered
    let already_exists = arr.iter().any(|h| {
        h.get("matcher").and_then(|m| m.as_str()) == Some("Write|Edit")
    });

    if !already_exists {
        arr.push(serde_json::json!({
            "matcher": "Write|Edit",
            "hooks": [{"type": "command", "command": "bash .corvia/hooks/doc-placement-check.sh"}]
        }));
        let content = serde_json::to_string_pretty(&settings)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to serialize: {e}")))?;
        std::fs::write(&settings_path, content)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to write: {e}")))?;
        println!("  Updated: {}", settings_path.display());
    } else {
        println!("  Skipped: {} (Write|Edit hook already registered)", settings_path.display());
    }
    Ok(())
}
