//! Hook generation for workspace doc enforcement.
//!
//! Reads [workspace.docs.rules] from corvia.toml and generates:
//! - .corvia/hooks/doc-placement-check.sh (PreToolUse validation)
//! - repos/*/.git/hooks/post-commit (git-triggered incremental re-index)
//! - .claude/settings.json merge (hook registration)

use corvia_common::config::{CorviaConfig, DocsRulesConfig};
use corvia_common::errors::Result;
use std::path::Path;

/// Characters unsafe to interpolate into bash case patterns or double-quoted strings.
const UNSAFE_BASH_CHARS: &[char] = &[')', '"', '$', '`', '\n', '\\', '\'', ';', '|', '&'];

pub fn generate_hooks(root: &Path, config: &CorviaConfig) -> Result<()> {
    let ws = config.workspace.as_ref()
        .ok_or_else(|| corvia_common::errors::CorviaError::Config("Not a workspace".into()))?;

    let rules = ws.docs.as_ref()
        .and_then(|d| d.rules.as_ref())
        .cloned()
        .unwrap_or_default();

    let allowed_subdirs = ws.docs.as_ref()
        .map(|d| d.allowed_workspace_subdirs.clone())
        .unwrap_or_default();

    generate_placement_hook(root, &rules, &allowed_subdirs)?;
    generate_post_commit_hooks(root, ws)?;
    merge_claude_settings(root)?;

    println!("Generated enforcement hooks from corvia.toml");
    Ok(())
}

fn generate_placement_hook(
    root: &Path,
    rules: &DocsRulesConfig,
    allowed_subdirs: &[String],
) -> Result<()> {
    let hook_dir = root.join(".corvia/hooks");
    std::fs::create_dir_all(&hook_dir)
        .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to create hooks dir: {e}")))?;

    // Sanitize blocked_paths: reject patterns with bash-unsafe characters
    let safe_blocked: Vec<&str> = rules.blocked_paths.iter()
        .filter(|p| {
            let safe = !p.chars().any(|c| UNSAFE_BASH_CHARS.contains(&c));
            if !safe {
                eprintln!("  Warning: skipping unsafe blocked_path pattern: {:?}", p);
            }
            safe
        })
        .map(|s| s.as_str())
        .collect();

    let blocked_cases: String = safe_blocked.iter()
        .map(|p| format!(
            "  {})\n    echo \"BLOCKED: file is in blocked path '{}'. Save product docs to repos/<repo>/docs/ instead.\" >&2\n    exit 2\n    ;;",
            p, p
        ))
        .collect::<Vec<_>>()
        .join("\n");

    // Build allow-list from config: repos/*/docs/* + docs/<subdir>/* for each allowed subdir
    let mut allow_patterns = vec!["repos/*/docs/*".to_string()];
    for subdir in allowed_subdirs {
        // Sanitize subdir names too
        if !subdir.chars().any(|c| UNSAFE_BASH_CHARS.contains(&c)) {
            allow_patterns.push(format!("docs/{}/*", subdir));
        }
    }
    let allow_list = allow_patterns.join("|");

    let script = format!(r#"#!/usr/bin/env bash
set -euo pipefail
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.file_path // empty')
[ -z "$FILE_PATH" ] && exit 0
# Strip workspace prefix to get relative path (Claude Code sends absolute paths)
FILE_PATH="${{FILE_PATH#$PWD/}}"
case "$FILE_PATH" in *.md|*.mdx|*.rst) ;; *) exit 0 ;; esac
case "$FILE_PATH" in
  # Common root-level files — always allowed
  README.md|CLAUDE.md|AGENTS.md|CHANGELOG.md|CONTRIBUTING.md|LICENSE.md)
    exit 0 ;;
  # Agent skills and config — always allowed
  .agents/*)
    exit 0 ;;
{blocked_cases}
  {allow_list})
    exit 0 ;;
esac
echo "NOTE: '$FILE_PATH' is in an unusual location for docs." >&2
exit 0
"#);

    let path = hook_dir.join("doc-placement-check.sh");
    std::fs::write(&path, script)
        .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to write hook: {e}")))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to chmod: {e}")))?;
    }

    println!("  Created: {}", path.display());
    Ok(())
}

fn generate_post_commit_hooks(
    root: &Path,
    ws: &corvia_common::config::WorkspaceConfig,
) -> Result<()> {
    for repo in &ws.repos {
        let git_hooks_dir = root.join(&ws.repos_dir).join(&repo.name).join(".git/hooks");
        if !git_hooks_dir.exists() {
            println!("  Skipped: {} (no .git directory)", repo.name);
            continue;
        }

        let hook = r#"#!/usr/bin/env bash
# Generated by: corvia workspace init-hooks
# Triggers incremental re-indexing of changed files after each commit.
command -v corvia >/dev/null 2>&1 || exit 0
changed=$(git diff-tree --no-commit-id --name-only -r HEAD)
docs_changed=$(echo "$changed" | grep -E '\.(md|toml|yaml|json|rs|py|ts|js)$' || true)
if [ -n "$docs_changed" ]; then
    echo "$docs_changed" | xargs -d '\n' corvia ingest --incremental --files >> /tmp/corvia-ingest.log 2>&1 &
fi
"#;

        let path = git_hooks_dir.join("post-commit");

        // Back up existing hook if present (don't clobber user hooks)
        if path.exists() {
            let existing = std::fs::read_to_string(&path).unwrap_or_default();
            if !existing.contains("corvia workspace init-hooks") {
                let backup = path.with_extension("pre-corvia.bak");
                std::fs::rename(&path, &backup)
                    .map_err(|e| corvia_common::errors::CorviaError::Config(
                        format!("Failed to backup existing hook: {e}"),
                    ))?;
                println!("  Backed up existing hook: {}", backup.display());
            }
        }

        std::fs::write(&path, hook)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to write hook: {e}")))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
                .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to chmod: {e}")))?;
        }

        println!("  Created: {}", path.display());
    }
    Ok(())
}

/// Merge the PreToolUse Write|Edit hook into .claude/settings.json
fn merge_claude_settings(root: &Path) -> Result<()> {
    let settings_dir = root.join(".claude");
    std::fs::create_dir_all(&settings_dir)
        .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to create .claude dir: {e}")))?;

    let settings_path = settings_dir.join("settings.json");
    let mut settings: serde_json::Value = if settings_path.exists() {
        let content = std::fs::read_to_string(&settings_path)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to read settings: {e}")))?;
        serde_json::from_str(&content)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to parse settings: {e}")))?
    } else {
        serde_json::json!({})
    };

    // Ensure root is an object
    let root_obj = settings.as_object_mut()
        .ok_or_else(|| corvia_common::errors::CorviaError::Config(
            "settings.json root is not a JSON object".into(),
        ))?;

    // Ensure hooks is an object
    let hooks = root_obj.entry("hooks").or_insert(serde_json::json!({}));
    let hooks_obj = hooks.as_object_mut()
        .ok_or_else(|| corvia_common::errors::CorviaError::Config(
            "settings.json 'hooks' is not a JSON object".into(),
        ))?;

    // Ensure PreToolUse is an array
    let pre_tool = hooks_obj.entry("PreToolUse").or_insert(serde_json::json!([]));
    let arr = pre_tool.as_array_mut()
        .ok_or_else(|| corvia_common::errors::CorviaError::Config(
            "settings.json 'hooks.PreToolUse' is not a JSON array".into(),
        ))?;

    // Check if Write|Edit hook already registered
    let already_exists = arr.iter().any(|h| {
        h.get("matcher").and_then(|m| m.as_str()) == Some("Write|Edit")
    });

    if !already_exists {
        arr.push(serde_json::json!({
            "matcher": "Write|Edit",
            "hooks": [{"type": "command", "command": "bash .corvia/hooks/doc-placement-check.sh"}]
        }));
        let content = serde_json::to_string_pretty(&settings)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to serialize: {e}")))?;
        std::fs::write(&settings_path, content)
            .map_err(|e| corvia_common::errors::CorviaError::Config(format!("Failed to write: {e}")))?;
        println!("  Updated: {}", settings_path.display());
    } else {
        println!("  Skipped: {} (Write|Edit hook already registered)", settings_path.display());
    }
    Ok(())
}
